### ISSUE TITLE
clfags are only targeting linux right now

### ISSUE THREAD

**Issue by james2doyle** [EmmaTheMartian/raylib-for-v#4]
I think this is all the changes that are needed to get OSX working right:

```diff
-#flag -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
+#flag linux -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
+#flag darwin -lraylib -lm -framework Foundation -framework AppKit -framework OpenGL -framework CoreVideo
```

I'm not a vlang expert nor a C one either - so this could be wrong? I used the vlang source to find some examples of multiple platform support in a C wrapper

**Comment by EmmaTheMartian** [comment]
I only use Linux for development so I'll just have to trust you on this. If someone wants to contribute the Windows flags then that would be great.
